### ISSUE TITLE
Kibana fails to connect to Elasticsearch node.

### ISSUE THREAD

**Issue by sanderpost** [deviantony/fig-elk#8]
Hi,

I got the nodes running (thnx for the works!) but it seems there's an issue between Kibana 3 and the Elasticsearch version started by this compose. Straight of the bat it gives me the following message:
![image](https://cloud.githubusercontent.com/assets/4763278/7940465/4891f666-0951-11e5-8096-44b4bf060329.png)

Cors does seem to be enabled in elasticsearch: 
![image](https://cloud.githubusercontent.com/assets/4763278/7940527/d3de3fea-0951-11e5-935a-d3ec15406bb5.png)

Any ideas? Editing the elasticsearch config is not really ez in the container btw. Is it possible to put that in an accessible folder as well? Just like the logstash config?

**Comment by deviantony** [comment]
Weird, do you access the Kibana UI via http://localhost:8080 ?

If you want to specify your own Elasticsearch configuration, add a volume to the elasticsearch container in the *docker-compose.yml*. Such as:

````
elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - elasticsearch-conf:/etc/elasticsearch
````

And then add your configuration file *elasticsearch.yml* in the elasticsearch-conf folder.

Keep me informed if you solve your issue.
